spring:
  application:
    name: service-one
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

servo:
  collection-interval-ms: 10000
  zipkin:
    endpoint: ${ZIPKIN_URI:http://localhost:9411/api/v2/spans}
