spring:
  application:
    name: service-one
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
  instance:
    preferIpAddress: true

servo:
  collection-interval-ms: 10000
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans