version: "3"

services:
  couchbase:
    container_name: couchbase
    image: arungupta/couchbase
    environment:
      COUCHBASE_SERVER_VERSION: latest
      COUCHBASE_ADMINISTRATOR_USERNAME: admin
      COUCHBASE_ADMINISTRATOR_PASSWORD: pass
      COUCHBASE_BUCKET: users
    deploy:
      replicas: 1
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"

  client:
    container_name: "nosql-client"
    build: .
    ports:
      - "8081:8081"
    links:
      - couchbase
    depends_on:
      - couchbase